### ISSUE TITLE
inference Error 

### ISSUE THREAD

**Issue by veonua** [kinhong/OpenLabeler#13]
2020-02-07 15:51:40 WARNING com.easymobo.openlabeler.ui.TagGroup: Fail to detect 
java.io.IOException: Expected 3-byte BGR encoding in BufferedImage, found 0. This code could be made more robust
	at com.easymobo.openlabeler.tensorflow.ObjectDetector.makeImageTensor(ObjectDetector.java:261)
	at com.easymobo.openlabeler.tensorflow.ObjectDetector.detect(ObjectDetector.java:158)
	at com.easymobo.openlabeler.ui.TagGroup.lambda$findHints$36(TagGroup.java:501)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by kinhong** [comment]
@veonua According to the stack trace, OpenLabeler's object detector is expecting an image with 8-bit RGB color components with no alpha. Could you please post the image (or a compatible sample) in question?

**Comment by veonua** [comment]
it's an invoice, so I can not share it publicly.

but it might be greyscale image. is it possible to force convert all images
to the same format

**Comment by kinhong** [comment]
@veonua In the new [v1.2.3](https://github.com/kinhong/OpenLabeler/releases/tag/v1.2.3) build, it will convert 8 and 16-bit grayscale images for object detection.
