### ISSUE TITLE
Unable to use model exported as 'encoded_image_string_tensor' 

### ISSUE THREAD

**Issue by veonua** [kinhong/OpenLabeler#15]
```
2020-03-06 10:59:04 WARNING com.easymobo.openlabeler.ui.TagGroup: Fail to detect 
java.lang.IllegalArgumentException: No Operation named [image_tensor] in the Graph
	at org.tensorflow.Session$Runner.operationByName(Session.java:384)
	at org.tensorflow.Session$Runner.parseOutput(Session.java:393)
	at org.tensorflow.Session$Runner.feed(Session.java:132)
	at com.easymobo.openlabeler.tensorflow.ObjectDetector.detect(ObjectDetector.java:161)
	at com.easymobo.openlabeler.ui.TagGroup.lambda$findHints$36(TagGroup.java:501)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
> `encoded_image_string_tensor`: Accepts a 1-D string tensor of shape [None]
>     containing encoded PNG or JPEG images. Image resolutions are expected to be
>     the same if more than 1 image is provided.
>

so it would be nice if OpenLabeler could check if 'encoded_image_string_tensor' operation is available, and can send image png to the endpoint

**Comment by kinhong** [comment]
@veonua Good point. I have added support for graphs with `encoded_image_string_tensor` operation. Please check out [v1.2.4](https://github.com/kinhong/OpenLabeler/releases/tag/v1.2.4).

**Comment by veonua** [comment]
thank you
