### ISSUE TITLE
TF error

### ISSUE THREAD

**Issue by krzynio** [kinhong/OpenLabeler#16]
Hi,

I have finetuned the model but inference does not work. It was trained with your docker image (gpu).

2020-05-16 09:31:03.185350: I tensorflow/cc/saved_model/reader.cc:54] Reading meta graph with tags { serve }
2020-05-16 09:31:03.253808: I tensorflow/cc/saved_model/loader.cc:202] Restoring SavedModel bundle.
2020-05-16 09:31:03.434418: I tensorflow/cc/saved_model/loader.cc:151] Running initialization op on SavedModel bundle at path: /home/krzynio/Pobrane/ssd_mobilenet_v1_coco_2018_01_28/train/export/Servo/1589595393
2020-05-16 09:31:03.491558: I tensorflow/cc/saved_model/loader.cc:311] SavedModel load for tags { serve }; Status: success. Took 320378 microseconds.
2020-05-16 09:31:03 INFO    com.easymobo.openlabeler.tensorflow.ObjectDetector: Loaded saved model from /home/krzynio/Pobrane/ssd_mobilenet_v1_coco_2018_01_28/train/export/Servo/1589595393 
2020-05-16 09:31:03 INFO    com.easymobo.openlabeler.tensorflow.ObjectDetector: MODEL SIGNATURE 
2020-05-16 09:31:03 INFO    com.easymobo.openlabeler.tensorflow.ObjectDetector: Inputs: 
2020-05-16 09:31:03 INFO    com.easymobo.openlabeler.tensorflow.ObjectDetector: 1 of 1: serialized_example   (Node name in graph: tf_example:0        , type: DT_STRING) 
2020-05-16 09:31:03 INFO    com.easymobo.openlabeler.tensorflow.ObjectDetector: Outputs: 
2020-05-16 09:31:03 INFO    com.easymobo.openlabeler.tensorflow.ObjectDetector: 1 of 4: detection_classes    (Node name in graph: detection_classes:0 , type: DT_FLOAT) 
2020-05-16 09:31:03 INFO    com.easymobo.openlabeler.tensorflow.ObjectDetector: 2 of 4: num_detections       (Node name in graph: num_detections:0    , type: DT_FLOAT) 
2020-05-16 09:31:03 INFO    com.easymobo.openlabeler.tensorflow.ObjectDetector: 3 of 4: detection_boxes      (Node name in graph: detection_boxes:0   , type: DT_FLOAT) 
2020-05-16 09:31:03 INFO    com.easymobo.openlabeler.tensorflow.ObjectDetector: 4 of 4: detection_scores     (Node name in graph: detection_scores:0  , type: DT_FLOAT) 
2020-05-16 09:31:03 INFO    com.easymobo.openlabeler.tensorflow.ObjectDetector: ----------------------------------------------- 
2020-05-16 09:31:06 WARNING com.easymobo.openlabeler.ui.TagBoard: Fail to detect 
java.lang.IllegalArgumentException: No Operation named [] in the Graph
	at org.tensorflow.Session$Runner.operationByName(Session.java:384)
	at org.tensorflow.Session$Runner.parseOutput(Session.java:393)
	at org.tensorflow.Session$Runner.feed(Session.java:132)
	at com.easymobo.openlabeler.tensorflow.ObjectDetector.detect(ObjectDetector.java:170)
	at com.easymobo.openlabeler.ui.TagBoard.lambda$findHints$36(TagBoard.java:500)
	at java.base/java.lang.Thread.run(Thread.java:834)

2020-05-16 09:31:07 WARNING com.easymobo.openlabeler.ui.TagBoard: Fail to detect 
java.lang.IllegalArgumentException: No Operation named [] in the Graph
	at org.tensorflow.Session$Runner.operationByName(Session.java:384)
	at org.tensorflow.Session$Runner.parseOutput(Session.java:393)
	at org.tensorflow.Session$Runner.feed(Session.java:132)
	at com.easymobo.openlabeler.tensorflow.ObjectDetector.detect(ObjectDetector.java:170)
	at com.easymobo.openlabeler.ui.TagBoard.lambda$findHints$36(TagBoard.java:500)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by kinhong** [comment]
@krzynio - from the log entries, it seems that the model is missing the `image_tensor` or the `encoded_image_string_tensor` input operations that OpenLabeler requires to perform object detection. Also, the output operation: `detection_scores` is missing. Here is a typical model signature that works:
`MODEL SIGNATURE`
`Inputs:`
`1 of 1: inputs               (Node name in graph: image_tensor:0      , type: DT_UINT8)`
`Outputs:`
`1 of 6: detection_classes    (Node name in graph: detection_classes:0 , type: DT_FLOAT)`
`2 of 6: num_detections       (Node name in graph: num_detections:0    , type: DT_FLOAT)`
`3 of 6: detection_boxes      (Node name in graph: detection_boxes:0   , type: DT_FLOAT)`
`4 of 6: raw_detection_boxes  (Node name in graph: raw_detection_boxes:0, type: DT_FLOAT)`
`5 of 6: detection_scores     (Node name in graph: detection_scores:0  , type: DT_FLOAT)`
`6 of 6: raw_detection_scores (Node name in graph: raw_detection_scores:0, type: DT_FLOAT)`
