### ISSUE TITLE
Problems on German System

### ISSUE THREAD

**Issue by Ryvid** [kinhong/OpenLabeler#4]
Hello,

i tried running this app on a system with german set as systemlanguage and it would not start. It throws the following error: 
```
2019-08-05 11:17:14 SEVERE  com.easymobo.openlabeler.OpenLabeler: Unable to start application 
java.util.MissingResourceException: Can't find bundle for base name bundle, locale de_DE
	at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2055)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1689)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1556)
	at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:857)
	at com.easymobo.openlabeler.OpenLabeler$1.call(OpenLabeler.java:74)
	at com.easymobo.openlabeler.OpenLabeler$1.call(OpenLabeler.java:70)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Is there anything like a fallback language or do i have to change to en_US for my systemlanguage?

**Comment by kinhong** [comment]
Hi @Ryvid, what OS were you running on?

**Comment by Ryvid** [comment]
The system is running Windows 10

**Comment by kinhong** [comment]
@Ryvid, I have uploaded an update which should default locale to en_US. Please try v1.1.2.

**Comment by Ryvid** [comment]
It's working fine now! Thanks.
